server:
  port: 9001
  error:
    include:
      message: true

grpc:
  server:
    port: 9002

spring:
  application:
    name: rangiffler-userdata
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 10000
      auto-commit: true
    username: postgres
    password: secret
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/rangiffler-userdata
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rangiffler-userdata'
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: 'localhost:9092'
    consumer:
      group-id: 'userdata'
      auto-offset-reset: earliest