server:
  port: 9005
  error:
    include:
      message: true

grpc:
  server:
    port: 9006
    max-inbound-message-size: 10485760

spring:
  application:
    name: rangiffler-photo
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 10000
      auto-commit: true
    username: postgres
    password: secret
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/rangiffler-photo
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
  sql:
    init:
      mode: always
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.boot: INFO
    org.springframework.security: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.context: INFO
---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rangiffler-photo'
    username: postgres
    password: secret

  jpa:
    hibernate:
      ddl-auto: validate
grpc:
  client:
    grpcUserdataClient:
      address: 'static://localhost:9002'
      negotiationType: PLAINTEXT
    grpcGeoClient:
      address: 'static://localhost:9004'
      negotiationType: PLAINTEXT