server:
  port: 9000
  servlet:
    session:
      cookie:
        http-only: false
        secure: false

spring:
  application:
    name: rangiffler-auth
  mvc:
    log-request-details: true
  datasource:
    hikari:
      connection-timeout: 5000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/rangiffler-auth
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    open-in-view: false

logging:
  file:
    path: ./logs/rangiffler-auth
  level:
    root: INFO
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.web.cors: INFO
    org.apache.catalina.filters.RequestDumperFilter: INFO
    org.springframework.boot.autoconfigure: INFO

---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  kafka:
    bootstrap-servers: 'localhost:9092'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rangiffler-auth'
    username: postgres
    password: secret
rangiffler-front:
  base-uri: 'http://127.0.0.1:3001'
rangiffler-auth:
  base-uri: 'http://127.0.0.1:9000'
oauth2:
  client-id: 'client'
  client-secret: '{noop}secret'


---
spring:
  config:
    activate:
      on-profile: 'docker'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  kafka:
    bootstrap-servers: 'rangiffler-all-kafka:9092'
  datasource:
    url: 'jdbc:postgresql://rangiffler-all-db:5432/rangiffler-auth'
    username: postgres
    password: secret
rangiffler-front:
  base-uri: 'http://frontend.rangiffler.dc'
rangiffler-auth:
  base-uri: 'http://auth.rangiffler.dc:9000'
oauth2:
  client-id: 'client'
  client-secret: '{noop}secret'